### ISSUE TITLE
Please remove blue color

### ISSUE THREAD

**Issue by iamsergii** [HookyQR/VSCodeCreateModule#1]
This looks ugly and unreadable on dark theme, on the other hand, underline is just perfect for most of color themes

**Comment by HookyQR** [comment]
Agreed. I've changed the color for dark themes to the same as the link color in the default vs-dark theme (#4E94CE) which looks pretty nice to me. Released new version. Give it a go and let me know if that will do the trick.

**Comment by iamsergii** [comment]
yeah, now color is better, but in my case it's still does not look with the other strings in the document (I use Ocean Next color theme). I removed color decoration in your plugin and it's much better for me now. 

IMHO it's not a good practice to hardcode the color inside the plugin with no possibility to change it.

<img width="478" alt="screenshot at jan 24 21-06-55" src="https://cloud.githubusercontent.com/assets/5055407/12538637/cef24660-c2de-11e5-894d-4b515a0ac6af.png">

<img width="480" alt="screenshot at jan 24 21-09-34" src="https://cloud.githubusercontent.com/assets/5055407/12538638/cef2ed04-c2de-11e5-9977-cfd1018f90d4.png">

**Comment by HookyQR** [comment]
I would have liked the extension to set the link color to what ever the users color theme uses, but I can't see a way to do this at the moment.

Having said that, I removed the colors completely from mine to see the effect. Since `Cmd` (or `Ctrl`) hover highlights as a link I'm going to drop the color change and leave it as just the underline per your initial suggestion.

Extension updated.

**Comment by iamsergii** [comment]
Thanks!
